app/Http/routes.php
    Route::DELETE('purchaseorderdetail/{tn}/podetail/{item}', 'PurchaseOrderDetailsController@destroy');
    Route::get('getrmcost', 'SalesOrderDetailController@getrmcost');
    Route::get('updateaup', 'SalesOrderDetailController@updateaup');
    Route::DELETE('salesorderdetail/{tn}/sod/{item}', 'SalesOrderDetailController@destroy');
    Route::get('salesorderdetail/{sodtnumber}/sodetail/{soditem}/edit', 'SalesOrderDetailController@edit');
    Route::get('getcurrencycustomer', 'SalesOrderController@currencycustomer');
    Route::get('getcurrencies', 'SalesOrderController@getcurrencies');
    Route::get('convertcurrency', 'SalesOrderController@convertcurrency');
    Route::get('currencyexcept', 'SalesOrderController@currencyexcept');
    Route::DELETE('currencyconvertion/{bcon}/convertion/{tarcon}', 'CurrencyconvertionController@destroy');
    Route::get('currencyconvertion/{cur1}', ['as'=>'createconvertions' ,'uses'=> 'CurrencyconvertionController@create']);
    Route::get('getcurrenciesrate', 'SalesOrderController@getcurrenciesrate');
    Route::get('getselectedrmformr', 'MaterialRequestDetailController@getselectedrmformr');


    Route::resource('company', 'CompaniesController');
    Route::resource('branch', 'BranchCompanyController');
    Route::resource('paymentterm', 'PaymentTermController');
    Route::resource('unitofmeasure', 'UnitOfMeasureController');
    Route::resource('customer', 'CustomerController');
    Route::resource('location', 'LocationController');
    Route::resource('box', 'BoxController');
    Route::resource('vendortype', 'VendorTypeController');
    Route::resource('vendors', 'VendorController');
    Route::resource('packaging', 'PackagingController');
    Route::resource('category', 'CategoryController');
    Route::resource('clss', 'ClassController');
    Route::resource('subclss', 'SubClassController');
    Route::resource('item', 'ItemsController');
    Route::resource('customer.contact', 'ContactController');
    Route::resource('vendors.contact', 'VendorContactController');
    Route::resource('rawmaterial', 'RawMaterialController');
    Route::resource('finishedproduct', 'FinishedProductController');
    Route::resource('rawmaterial.venditem', 'VendorItemController');
    Route::resource('rawmaterial.itempacking', 'ItemPackingController');
    Route::resource('finishedproduct.otherproduct', 'OtherProductController');
    Route::resource('finishedproduct.bom', 'BillOfMaterialController');
    Route::resource('finishedproduct.finishedpacking', 'FinishedPackingController');
    Route::resource('supplies', 'SuppliesController');
    Route::resource('supplies.suppliesvendor', 'SuppliesVendorController');
    Route::resource('supplies.suppliesitempacking', 'SuppliesItemPackingController');
    Route::resource('usercontrol', 'UserControlController');
    Route::resource('securityuser', 'UserSecurityController');
    Route::resource('usergroup', 'UserGroupController');
    Route::resource('joborder', 'JobOrderController');
    Route::resource('joborderdetail', 'JobOrderDetailsController');
    Route::resource('purchasing', 'PurchasingController');
    Route::resource('joborder.joborderbom', 'JobOrderBomController');
    Route::resource('purchaseorderdetail', 'PurchaseOrderDetailsController');
    Route::resource('purchasebalance', 'PurchaseBalanceController');
    Route::resource('poinstruction', 'PoInstructionController');
    Route::resource('salesorder', 'SalesOrderController');
    Route::resource('salesorderdetail', 'SalesOrderDetailController');
    Route::resource('positions', 'PositionController');
    Route::resource('currency', 'CurrencyController');
    Route::resource('currencyconvertion', 'CurrencyconvertionController');

    Route::resource('receiving', 'ReceivingController');
    Route::resource('production', 'ProductionController');
    Route::resource('materialrequest', 'MaterialRequestController');
    Route::resource('materialrequestdetail', 'MaterialRequestDetailController');

    Route::resource('unitofmeasureconvertion', 'UomconvertionController');
    Route::resource('processs', 'ProcessController');


    Route::get('dashboard/customer', 'DatatablesController@customer');
    Route::get('dashboard/company', 'DatatablesController@company');
    Route::get('dashboard/branch', 'DatatablesController@branch');
    Route::get('dashboard/paymentterm', 'DatatablesController@paymentterm');
    Route::get('dashboard/unitofmeasure', 'DatatablesController@unitofmeasure');
    Route::get('dashboard/locat', 'DatatablesController@locat');
    Route::get('dashboard/box', 'DatatablesController@box');
    Route::get('dashboard/vendortype', 'DatatablesController@vendortype');
    Route::get('dashboard/vendors', 'DatatablesController@vendors');
    Route::get('dashboard/packaging', 'DatatablesController@packaging');
    Route::get('dashboard/category', 'DatatablesController@category');
    Route::get('dashboard/clss', 'DatatablesController@clss');
    Route::get('dashboard/subclss', 'DatatablesController@subclss');
    Route::get('dashboard/item', 'DatatablesController@item');
    Route::get('customer/{d}/custcontact', 'DatatablesController@custcontact');
    Route::get('vendors/{d}/vendorcontact', 'DatatablesController@vendorcontact');
    Route::get('dashboard/rawmaterial', 'DatatablesController@rawmaterial');
    Route::get('dashboard/finishedproduct', 'DatatablesController@finishedproduct');
    Route::get('rawmaterial/{rid}/rawmatvenditem', 'DatatablesController@rawmatvenditem');
    Route::get('rawmaterial/{rid}/rawmatitempackaging', 'DatatablesController@rawmatitempackaging');
    Route::get('finishedproduct/{rid}/otherproducts', 'DatatablesController@otherproducts');
    Route::get('finishedproduct/{rid}/fpbom', 'DatatablesController@bom');
    Route::get('finishedproduct/{rid}/fppack', 'DatatablesController@finishedpacking');
    Route::get('process/getprocess', 'DatatablesController@process');
    Route::get('dashboard/supplies', 'DatatablesController@supplies');
    Route::get('supplies/{rid}/suppliesvend', 'DatatablesController@suppliesvend');
    Route::get('supplies/{rid}/suppliesitempack', 'DatatablesController@suppliesitempack');
    Route::get('dashboard/securityuser', 'DatatablesController@securityuser');
    Route::get('dashboard/usergroup', 'DatatablesController@usergroup');
    Route::get('dashboard/joborderlist', 'DatatablesController@joborderlist');
    Route::get('jocust', 'DatatablesController@jocust');
    Route::get('jodetailfinishprod', 'DatatablesController@jodetailfinishprod');
    Route::get('joborder/{item}/jodetaillist', 'DatatablesController@jodetaillist');
    Route::get('dashboard/purchaseorderlist', 'DatatablesController@purchaseorderlist');
    Route::get('povendor', 'DatatablesController@povendor');
    Route::get('purchasing/{item}/podetaillist', 'DatatablesController@podetaillist');
    Route::get('purchasebalance/{item}/pobaldetaillist', 'DatatablesController@pobaldetaillist');
    Route::get('getpurchasedetail/{vendor}', 'DatatablesController@podetailfinishprod');
    Route::get('purchasebalance/{id}/view', 'PurchaseBalanceController@show');
    Route::get('purchasing/{item}/poinstructions/{poid}', 'DatatablesController@poinstructions');
    Route::get('joborder/{tn}/joborderbomgetbom', 'DatatablesController@getbom');
    Route::get('jobomlookup', 'DatatablesController@jobomlookup');
    Route::get('dashboard/salesoderlist', 'DatatablesController@salesoderlist');
    Route::get('salesorder/{so}/sodetaillist', 'DatatablesController@sodetaillist');
    Route::get('dashboard/positions', 'DatatablesController@positions');
    Route::get('dashboard/currency', 'DatatablesController@currency');
    Route::get('conlist/{conid}', 'DatatablesController@currencylist');
    Route::get('getprocesses', 'DatatablesController@getprocesses');
    Route::get('dashboard/purchaseorderbalancelist', 'DatatablesController@purchaseorderbalancelist'); 

    Route::get('receiving/{item}/receivingpodetail', 'DatatablesController@receivingpodetail');
    Route::get('production/{item}/prodjobomlist', 'DatatablesController@prodjobomlist');
    Route::get('mrjolist', 'DatatablesController@mrjolist');
    Route::get('solist', 'DatatablesController@solist');
    Route::get('materialrequest/{item}/mrdetaillist', 'DatatablesController@mrdetaillist');
    Route::get('getmrdetail/{tnumber}', 'DatatablesController@mrdetailitems');

    Route::get('dashboard/uomconvertion', 'DatatablesController@uomconvertion');

    Route::get('dashboard', ['as'=>'dashboard' ,'uses'=> 'DashBoardController@index']);
    Route::get('customer', ['as'=>'customer' ,'uses'=> 'CustomerController@index']);
    Route::get('company', ['as'=>'company' ,'uses'=> 'CompaniesController@index']);
    Route::get('company/create', ['as'=>'create' ,'uses'=> 'CompaniesController@create']);
    Route::get('company/{id}', ['as'=>'update' ,'uses'=> 'CompaniesController@update']);
    Route::get('branch', ['as'=>'branch' ,'uses'=> 'BranchCompanyController@index']);
    Route::get('paymentterm', ['as'=>'paymentterm' ,'uses'=> 'PaymentTermController@index']);
    Route::get('unitofmeasure', ['as'=>'unitofmeasure' ,'uses'=> 'UnitOfMeasureController@index']);
    Route::get('customer', ['as'=>'customer' ,'uses'=> 'CustomerController@index']);
    Route::get('location', ['as'=>'location' ,'uses'=> 'LocationController@index']);
    Route::get('box', ['as'=>'box' ,'uses'=> 'BoxController@index']);
    Route::get('vendortype', ['as'=>'vendortype' ,'uses'=> 'VendorTypeController@index']);
    Route::get('vendors', ['as'=>'vendors' ,'uses'=> 'VendorController@index']);
    Route::get('packaging', ['as'=>'packaging' ,'uses'=> 'PackagingController@index']);
    Route::get('category', ['as'=>'category' ,'uses'=> 'CategoryController@index']);
    Route::get('clss', ['as'=>'clss' ,'uses'=> 'ClassController@index']);
    Route::get('subclss', ['as'=>'subclss' ,'uses'=> 'SubClassController@index']);

app/PoInstruction.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class PoInstruction extends Model
{
    protected $table = 'mst_poinstructions';

    public $timestamps = false;

    protected $fillable = ['instruction'];


    public function purchaseinstruction(){
        return $this->hasMany('App\PurchaseOrderInstruction','_instruction');
    }
}

app/Http/Controllers/PoInstructionController.php
<?php

namespace App\Http\Controllers;

use App\PoInstruction;
use App\PurchaseOrderDetails;
use App\PurchaseOrderInstruction;
use Illuminate\Http\Request;

use App\Http\Requests;

class PoInstructionController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(Request $request)
    {
        $trn = $request->trnid;
        return view('poinstructions.create',compact('trn'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        // dd($request->all());
        $this->validate($request,[
            'instruction' => 'required',
        ]);

        $poinstruction = new PoInstruction($request->all());
        $poinstruction->save();

        $poorderins = new PurchaseOrderInstruction();
        $poorderins->tnumber = $request->trn;
        $poorderins->_instruction = $poinstruction->id;
        $poorderins->save();

        return redirect('purchase');
        //return response()->json(['return' => 'some data']);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/poinstructions/create.blade.php
@extends('layouts.layout')

@section('breadcrumbpage')
    <div class="row white-bg page-heading">
        <div class="col-lg-10">
            <h2>List of Purcahse Order Instructions</h2>
            {!! Breadcrumbs::render('purchasing') !!}
        </div>
        <div class="col-lg-2">

        </div>
    </div>
@endsection

@section('content')


    <div class="wrapper-content">
        <div class="row">
            <div class="col-lg-12">

                <div class="white-bg box-wrapper">
                    <div class="box-tool-bar">
                        <h5>Add PO Instructions</h5>

                    </div>

                    <div class="box-content white-bg">
                        <div class="row">
                               <div class="col-lg-6">

                                  <form class="form-horizontal" method="post" action="{{ route('poinstruction.store') }}">
                                      {{ csrf_field() }}
                                      <div class="form-group {{ $errors->has('instruction') ? ' has-error' : '' }}">
                                          <label class="col-sm-4 control-label">Instruction</label>

                                          <div class="col-sm-8">
                                            <input type="hidden" name="trn" value="{{$trn}}">
                                              <input type="text" name="instruction" class="form-control">
                                              @if ($errors->has('instruction'))
                                                  <span class="help-block">
                                                  <strong>{{ $errors->first('instruction') }}</strong>
                                                  </span>
                                              @endif

                                          </div>
                                      </div>

                                    <div class="hr-line-dashed"></div>
                                    <div class="form-group">
                                        <div class="col-sm-6 col-sm-offset-4">
                                            <a href="{{ URL::to('purchasing/'.$trn ).'/edit' }}" class="btn btn-white">Cancel</a>
                                            <button type="submit" class="btn btn-primary">Save </button>
                                        </div>
                                    </div>
                                </form>
                                </div>
                          </div>
                    </div>
                </div>

            </div>

        </div>
    </div>


@endsection

resources/views/poinstructions/edit.blade.php
@extends('layouts.layout')

@section('breadcrumbpage')
    <div class="row white-bg page-heading">
        <div class="col-lg-10">
            <h2>List of Companies</h2>
            {!! Breadcrumbs::render('company') !!}
        </div>
        <div class="col-lg-2">

        </div>
    </div>
@endsection

@section('content')


    <div class="wrapper-content">
        <div class="row">
            <div class="col-lg-12">

                <div class="white-bg box-wrapper">
                    <div class="box-tool-bar">
                        <h5>Edit Company</h5>

                    </div>

                    <div class="box-content white-bg">
                        <div class="row">
                               <div class="col-lg-6">

                                  <form  class="form-horizontal" method="POST" action="{{ route('company.update',$company->id) }}">
                                      {{ csrf_field() }}

                                      <input type="hidden" name="_method" value="PUT">
                                      <div class="form-group">
                                          <label class="col-sm-4 control-label">Code</label>

                                          <div class="col-sm-8">
                                              <input type="text" name="code"  value="{{ $company->code }}" class="form-control">

                                          </div>
                                      </div>


                                    <div class="form-group {{ $errors->has('name') ? ' has-error' : '' }}">
                                        <label class="col-sm-4 control-label">Name</label>

                                        <div class="col-sm-8">
                                            <input type="text" name="name"  value="{{ $company->name }}" class="form-control">
                                            @if ($errors->has('name'))
                                                <span class="help-block">
                                                  <strong>{{ $errors->first('name') }}</strong>
                                                  </span>
                                            @endif
                                        </div>
                                    </div>

                                    <div class="form-group {{ $errors->has('address') ? ' has-error' : '' }}">
                                        <label class="col-sm-4 control-label">Address</label>

                                        <div class="col-sm-8">
                                            <input type="text" name="address" value="{{ $company->address }}" class="form-control">
                                            @if ($errors->has('address'))
                                                <span class="help-block">
                                                  <strong>{{ $errors->first('address') }}</strong>
                                                  </span>
                                            @endif

                                        </div>
                                    </div>

                                      <div class="form-group {{ $errors->has('zipcode') ? ' has-error' : '' }}">
                                          <label class="col-sm-4 control-label">Zip code</label>

                                          <div class="col-sm-8">
                                              <input type="text" name="zipcode"  value="{{ $company->zipcode }}" class="form-control" placeholder="">
                                              @if ($errors->has('zipcode'))
                                                  <span class="help-block">
                                                  <strong>{{ $errors->first('zipcode') }}</strong>
                                                  </span>
                                              @endif
                                          </div>
                                      </div>

                                    <div class="form-group {{ $errors->has('tin') ? ' has-error' : '' }}">
                                        <label class="col-sm-4 control-label">Tin</label>

                                        <div class="col-sm-8">
                                            <input type="text" name="tin" value="{{ $company->tin }}" class="form-control">
                                            @if ($errors->has('tin'))
                                                <span class="help-block">
                                                  <strong>{{ $errors->first('tin') }}</strong>
                                                  </span>
                                            @endif
                                        </div>
                                    </div>


                                      <div class="form-group {{ $errors->has('glcode') ? ' has-error' : '' }}">
                                          <label class="col-sm-4 control-label">GL Code</label>

                                          <div class="col-sm-8">
                                              <input type="text" name="glcode" value="{{ $company->glcode }}" class="form-control">
                                              @if ($errors->has('glcode'))
                                                  <span class="help-block">
                                                  <strong>{{ $errors->first('glcode') }}</strong>
                                                  </span>
                                              @endif
                                          </div>
                                      </div>



                                      <div class="form-group">
                                          <div class="col-sm-6 col-sm-offset-4">
                                              <div>
                                                  <label>
                                                      @if($company->isactive)
                                                          <input type="checkbox" value="1" checked name="isactive">  Active
                                                      @else
                                                          <input type="checkbox" name="isactive">  Active

                                                      @endif

                                                  </label>
                                              </div>
                                          </div>
                                      </div>



                                    <div class="hr-line-dashed"></div>
                                    <div class="form-group">
                                        <div class="col-sm-6 col-sm-offset-4">
                                            <button type="submit" class="btn btn-white">Cancel</button>
                                            <button type="submit" class="btn btn-primary">Save </button>
                                        </div>
                                    </div>
                                </form>
                                </div>
                          </div>
                    </div>
                </div>

            </div>

        </div>
    </div>


@endsection




@section('customjs')

    <script src="{{ URL::asset('js/company.js') }}"></script>


@endsection