app/Http/routes.php
    Route::POST('vendorsearchid','VendorController@vendorsearchid');
    Route::get('verifycoderawmat','ItemsController@verifycoderawmat');
    Route::get('findrawmaterial','ItemsController@findrawmaterial');
    Route::POST('rawmaterial-search','ItemsController@rawmaterialsearch');
    Route::POST('rawmaterialsearchid','ItemsController@rawmaterialsearchid');
    Route::get('otherproductverifycode','OtherProductController@otherproductverifycode');
    Route::post('otherproductsearch','OtherProductController@otherproductsearch');
    Route::get('finished-otherproduct','OtherProductController@otherproductall');
    Route::POST('otherproductsearchid','OtherProductController@otherproductsearchid');
    Route::POST('costingsave','FinishedProductController@costingsave');
    Route::POST('costingupdate','FinishedProductController@costingupdate');
    Route::POST('costchanges','RawMaterialController@costchanges');
    Route::get('getcostchanges','RawMaterialController@getcostchanges');
    Route::POST('suppliescostchanges','SuppliesController@suppliescostchanges');
    Route::get('suppliesgetcostchanges','SuppliesController@suppliesgetcostchanges');
    Route::get('getselectedrm', 'BillOfMaterialController@getselectedrm');
    Route::get('getdroppacking','BillOfMaterialController@getdroppacking');
    Route::PUT('resetpassword','UserSecurityController@resetpassword');
    Route::get('getselecteditempacking', 'JobOrderDetailsController@getselecteditempacking');
    Route::DELETE('joborderdetail/{tn}/jodetail/{item}', 'JobOrderDetailsController@destroy');
    Route::get('getjodsellingprice', 'JobOrderDetailsController@getjodsellingprice');
    Route::get('accessroles', 'UserGroupController@accessroles');
    Route::get('getposellingprice', 'PurchaseOrderDetailsController@getposellingprice');
    Route::DELETE('purchaseorderdetail/{tn}/podetail/{item}', 'PurchaseOrderDetailsController@destroy');
    Route::get('getrmcost', 'SalesOrderDetailController@getrmcost');
    Route::get('updateaup', 'SalesOrderDetailController@updateaup');
    Route::DELETE('salesorderdetail/{tn}/sod/{item}', 'SalesOrderDetailController@destroy');
    Route::get('salesorderdetail/{sodtnumber}/sodetail/{soditem}/edit', 'SalesOrderDetailController@edit');
    Route::get('getcurrencycustomer', 'SalesOrderController@currencycustomer');
    Route::get('getcurrencies', 'SalesOrderController@getcurrencies');
    Route::get('convertcurrency', 'SalesOrderController@convertcurrency');
    Route::get('currencyexcept', 'SalesOrderController@currencyexcept');
    Route::DELETE('currencyconvertion/{bcon}/convertion/{tarcon}', 'CurrencyconvertionController@destroy');
    Route::get('currencyconvertion/{cur1}', ['as'=>'createconvertions' ,'uses'=> 'CurrencyconvertionController@create']);
    Route::get('getcurrenciesrate', 'SalesOrderController@getcurrenciesrate');
    Route::get('getselectedrmformr', 'MaterialRequestDetailController@getselectedrmformr');


    Route::resource('company', 'CompaniesController');
    Route::resource('branch', 'BranchCompanyController');
    Route::resource('paymentterm', 'PaymentTermController');
    Route::resource('unitofmeasure', 'UnitOfMeasureController');
    Route::resource('customer', 'CustomerController');
    Route::resource('location', 'LocationController');
    Route::resource('box', 'BoxController');
    Route::resource('vendortype', 'VendorTypeController');
    Route::resource('vendors', 'VendorController');
    Route::resource('packaging', 'PackagingController');
    Route::resource('category', 'CategoryController');
    Route::resource('clss', 'ClassController');
    Route::resource('subclss', 'SubClassController');
    Route::resource('item', 'ItemsController');
    Route::resource('customer.contact', 'ContactController');
    Route::resource('vendors.contact', 'VendorContactController');
    Route::resource('rawmaterial', 'RawMaterialController');
    Route::resource('finishedproduct', 'FinishedProductController');
    Route::resource('rawmaterial.venditem', 'VendorItemController');
    Route::resource('rawmaterial.itempacking', 'ItemPackingController');
    Route::resource('finishedproduct.otherproduct', 'OtherProductController');
    Route::resource('finishedproduct.bom', 'BillOfMaterialController');
    Route::resource('finishedproduct.finishedpacking', 'FinishedPackingController');
    Route::resource('supplies', 'SuppliesController');
    Route::resource('supplies.suppliesvendor', 'SuppliesVendorController');
    Route::resource('supplies.suppliesitempacking', 'SuppliesItemPackingController');
    Route::resource('usercontrol', 'UserControlController');
    Route::resource('securityuser', 'UserSecurityController');
    Route::resource('usergroup', 'UserGroupController');
    Route::resource('joborder', 'JobOrderController');
    Route::resource('joborderdetail', 'JobOrderDetailsController');
    Route::resource('purchasing', 'PurchasingController');
    Route::resource('joborder.joborderbom', 'JobOrderBomController');
    Route::resource('purchaseorderdetail', 'PurchaseOrderDetailsController');
    Route::resource('purchasebalance', 'PurchaseBalanceController');
    Route::resource('poinstruction', 'PoInstructionController');
    Route::resource('salesorder', 'SalesOrderController');
    Route::resource('salesorderdetail', 'SalesOrderDetailController');
    Route::resource('positions', 'PositionController');
    Route::resource('currency', 'CurrencyController');
    Route::resource('currencyconvertion', 'CurrencyconvertionController');

    Route::resource('receiving', 'ReceivingController');
    Route::resource('production', 'ProductionController');
    Route::resource('materialrequest', 'MaterialRequestController');
    Route::resource('materialrequestdetail', 'MaterialRequestDetailController');

    Route::resource('unitofmeasureconvertion', 'UomconvertionController');
    Route::resource('processs', 'ProcessController');


    Route::get('dashboard/customer', 'DatatablesController@customer');
    Route::get('dashboard/company', 'DatatablesController@company');
    Route::get('dashboard/branch', 'DatatablesController@branch');
    Route::get('dashboard/paymentterm', 'DatatablesController@paymentterm');
    Route::get('dashboard/unitofmeasure', 'DatatablesController@unitofmeasure');
    Route::get('dashboard/locat', 'DatatablesController@locat');
    Route::get('dashboard/box', 'DatatablesController@box');
    Route::get('dashboard/vendortype', 'DatatablesController@vendortype');
    Route::get('dashboard/vendors', 'DatatablesController@vendors');
    Route::get('dashboard/packaging', 'DatatablesController@packaging');
    Route::get('dashboard/category', 'DatatablesController@category');
    Route::get('dashboard/clss', 'DatatablesController@clss');
    Route::get('dashboard/subclss', 'DatatablesController@subclss');
    Route::get('dashboard/item', 'DatatablesController@item');
    Route::get('customer/{d}/custcontact', 'DatatablesController@custcontact');
    Route::get('vendors/{d}/vendorcontact', 'DatatablesController@vendorcontact');
    Route::get('dashboard/rawmaterial', 'DatatablesController@rawmaterial');
    Route::get('dashboard/finishedproduct', 'DatatablesController@finishedproduct');
    Route::get('rawmaterial/{rid}/rawmatvenditem', 'DatatablesController@rawmatvenditem');
    Route::get('rawmaterial/{rid}/rawmatitempackaging', 'DatatablesController@rawmatitempackaging');
    Route::get('finishedproduct/{rid}/otherproducts', 'DatatablesController@otherproducts');
    Route::get('finishedproduct/{rid}/fpbom', 'DatatablesController@bom');
    Route::get('finishedproduct/{rid}/fppack', 'DatatablesController@finishedpacking');
    Route::get('process/getprocess', 'DatatablesController@process');
    Route::get('dashboard/supplies', 'DatatablesController@supplies');
    Route::get('supplies/{rid}/suppliesvend', 'DatatablesController@suppliesvend');
    Route::get('supplies/{rid}/suppliesitempack', 'DatatablesController@suppliesitempack');
    Route::get('dashboard/securityuser', 'DatatablesController@securityuser');
    Route::get('dashboard/usergroup', 'DatatablesController@usergroup');
    Route::get('dashboard/joborderlist', 'DatatablesController@joborderlist');
    Route::get('jocust', 'DatatablesController@jocust');
    Route::get('jodetailfinishprod', 'DatatablesController@jodetailfinishprod');
    Route::get('joborder/{item}/jodetaillist', 'DatatablesController@jodetaillist');
    Route::get('dashboard/purchaseorderlist', 'DatatablesController@purchaseorderlist');
    Route::get('povendor', 'DatatablesController@povendor');
    Route::get('purchasing/{item}/podetaillist', 'DatatablesController@podetaillist');
    Route::get('purchasebalance/{item}/pobaldetaillist', 'DatatablesController@pobaldetaillist');
    Route::get('getpurchasedetail/{vendor}', 'DatatablesController@podetailfinishprod');
    Route::get('purchasebalance/{id}/view', 'PurchaseBalanceController@show');
    Route::get('purchasing/{item}/poinstructions/{poid}', 'DatatablesController@poinstructions');
    Route::get('joborder/{tn}/joborderbomgetbom', 'DatatablesController@getbom');
    Route::get('jobomlookup', 'DatatablesController@jobomlookup');
    Route::get('dashboard/salesoderlist', 'DatatablesController@salesoderlist');
    Route::get('salesorder/{so}/sodetaillist', 'DatatablesController@sodetaillist');
    Route::get('dashboard/positions', 'DatatablesController@positions');
    Route::get('dashboard/currency', 'DatatablesController@currency');
    Route::get('conlist/{conid}', 'DatatablesController@currencylist');
    Route::get('getprocesses', 'DatatablesController@getprocesses');
    Route::get('dashboard/purchaseorderbalancelist', 'DatatablesController@purchaseorderbalancelist'); 

    Route::get('receiving/{item}/receivingpodetail', 'DatatablesController@receivingpodetail');
    Route::get('production/{item}/prodjobomlist', 'DatatablesController@prodjobomlist');

app/Http/Controllers/VendorTypeController.php
<?php

namespace App\Http\Controllers;

use App\VendorType;
use Illuminate\Http\Request;

use App\Http\Requests;
use Gate;

class VendorTypeController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        if (Gate::denies('list')) {
            abort(403);
        }
        return view('vendortype.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        if (Gate::denies('create')) {
            abort(403);
        }
        return view('vendortype.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request,[
            'code' => 'required',
            'name' => 'required'


        ]);



        $company = new VendorType($request->all());
        $company->id = '3';
        $company->save();

        return redirect('vendortype');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        if (Gate::denies('edit')) {
            abort(403);
        }
        $company = VendorType::find($id);

        return view('vendortype.edit',compact('company'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $company = VendorType::find($id);
        $company->fill($request->all());
        $company->save();
        return redirect('vendortype');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        if (Gate::denies('delete')) {
            abort(403);
        }
        $company = VendorType::find($id);
        $company->delete();

        return response()->json(['ok'=>'success']);
    }
}

resources/views/vendortype/create.blade.php
@extends('layouts.layout')

@section('breadcrumbpage')
    <div class="row white-bg page-heading">
        <div class="col-lg-10">
            <h2>List of Vendor Type</h2>
            {!! Breadcrumbs::render('vendortype') !!}
        </div>
        <div class="col-lg-2">

        </div>
    </div>
@endsection

@section('content')


    <div class="wrapper-content">
        <div class="row">
            <div class="col-lg-12">

                <div class="white-bg box-wrapper">
                    <div class="box-tool-bar">
                        <h2>Add Vendor Type</h2>

                    </div>

                    <div class="box-content white-bg">
                        <div class="row">
                               <div class="col-lg-6">

                                  <form class="form-horizontal" method="post" action="{{ route('vendortype.store') }}">
                                      {{ csrf_field() }}
                                      <div class="form-group">
                                          <label class="col-sm-4 control-label">Code</label>

                                          <div class="col-sm-8">
                                              <input type="text" name="code"   class="form-control">

                                          </div>
                                      </div>


                                    <div class="form-group {{ $errors->has('name') ? ' has-error' : '' }}">
                                        <label class="col-sm-4 control-label">Vendor Type</label>

                                        <div class="col-sm-8">
                                            <input type="text" name="name"  value="{{ old('name') }}" class="form-control">
                                            @if ($errors->has('name'))
                                                <span class="help-block">
                                                  <strong>{{ $errors->first('name') }}</strong>
                                                  </span>
                                            @endif
                                        </div>
                                    </div>





                                    <div class="hr-line-dashed"></div>
                                    <div class="form-group">
                                        <div class="col-sm-6 col-sm-offset-4">
                                            <button type="submit" class="btn btn-white">Cancel</button>
                                            <button type="submit" class="btn btn-primary">Save </button>
                                        </div>
                                    </div>
                                </form>
                                </div>
                          </div>
                    </div>
                </div>

            </div>

        </div>
    </div>


@endsection


@section('customjs')

    <script src="{{ URL::asset('js/paymentterm.js') }}"></script>

@endsection

resources/views/vendortype/edit.blade.php
@extends('layouts.layout')

@section('breadcrumbpage')
    <div class="row white-bg page-heading">
        <div class="col-lg-10">
            <h2>List of Companies</h2>
            {!! Breadcrumbs::render('company') !!}
        </div>
        <div class="col-lg-2">

        </div>
    </div>
@endsection

@section('content')


    <div class="wrapper-content">
        <div class="row">
            <div class="col-lg-12">

                <div class="white-bg box-wrapper">
                    <div class="box-tool-bar">
                        <h2>Add Company</h2>

                    </div>

                    <div class="box-content white-bg">
                        <div class="row">
                               <div class="col-lg-6">

                                  <form  class="form-horizontal" method="POST" action="{{ route('vendortype.update',$company->id) }}">
                                      {{ csrf_field() }}

                                      <input type="hidden" name="_method" value="PUT">
                                      <div class="form-group">
                                          <label class="col-sm-4 control-label">Code</label>

                                          <div class="col-sm-8">
                                              <input type="text" name="code" readonly value="{{ $company->code }}" class="form-control">

                                          </div>
                                      </div>


                                    <div class="form-group {{ $errors->has('name') ? ' has-error' : '' }}">
                                        <label class="col-sm-4 control-label">Vendor Type</label>

                                        <div class="col-sm-8">
                                            <input type="text" name="name"  value="{{ $company->name }}" class="form-control">
                                            @if ($errors->has('name'))
                                                <span class="help-block">
                                                  <strong>{{ $errors->first('name') }}</strong>
                                                  </span>
                                            @endif
                                        </div>
                                    </div>






                                    <div class="hr-line-dashed"></div>
                                    <div class="form-group">
                                        <div class="col-sm-6 col-sm-offset-4">
                                            <button type="submit" class="btn btn-white">Cancel</button>
                                            <button type="submit" class="btn btn-primary">Save </button>
                                        </div>
                                    </div>
                                </form>
                                </div>
                          </div>
                    </div>
                </div>

            </div>

        </div>
    </div>


@endsection




@section('customjs')

    <script src="{{ URL::asset('js/paymentterm.js') }}"></script>


@endsection

resources/views/vendortype/index.blade.php
@extends('layouts.layout')

@section('breadcrumbpage')
    <div class="row white-bg page-heading">
        <div class="col-lg-10">
            <h2>List of Vendor Type</h2>
            {!! Breadcrumbs::render('vendortype') !!}
        </div>
        <div class="col-lg-2">

        </div>
    </div>
@endsection

@section('content')


    <div class="wrapper-content">
        <div class="row">
            <div class="col-lg-12">

                <div class="white-bg box-wrapper">

                    <div class="ibox-title">
                        <h5>Payment term
                            <small></small>
                        </h5>
                        <div class="ibox-tools">

                            <a href="#" data-toggle="dropdown" class="dropdown-toggle">
                                <i class="fa fa-cog"></i>
                            </a>
                            <ul class="dropdown-menu">
                                <li><a href="{{ URL::to('vendortype/create') }}">Add Vendor Type</a>
                                </li>

                            </ul>

                        </div>
                    </div>

                    <div class="box-content white-bg">
                        <div class="table-responsive">
                            <table width="100%" class="table table-bordered table-striped" id="vendortype-table">
                                <thead>
                                <tr>
                                    <th>Code</th>
                                    <th>Type Name</th>

                                    <th>Action</th>

                                </tr>
                                </thead>

                            </table>
                        </div>
                    </div>

                </div>

            </div>

        </div>
    </div>


@endsection

@section('customjs')

    <script src="{{ URL::asset('js/vendortype.js') }}"></script>


@endsection