app/Http/routes.php
<?php

/*\DB::listen(function($query){

    \Log::info($query->sql);
});*/


Route::auth();

Route::group(['middleware' => ['auth']], function () {

    Route::get('/', 'DashBoardController@index');

    Route::get('contact/delcutcontact/{d}', 'ContactController@destroy');
    Route::get('rawmaterial/getcategory', 'RawMaterialController@getcategory');
    Route::get('rawmaterial/getclss', 'RawMaterialController@getclss');
    Route::get('rawmaterial/getsubclass', 'RawMaterialController@getsubclass');
    Route::get('rawmaterial/geteditcategory', 'RawMaterialController@geteditcategory');
    Route::get('finishedproduct/getcategory', 'FinishedProductController@getcategory');
    Route::get('finishedproduct/getclss', 'FinishedProductController@getclss');
    Route::get('finishedproduct/getsubclass', 'FinishedProductController@getsubclass');
    Route::get('finishedproduct/geteditcategory', 'FinishedProductController@geteditcategory');
    Route::get('supplies/getcategory', 'SuppliesController@getcategory');
    Route::get('supplies/getclss', 'SuppliesController@getclss');
    Route::get('supplies/getsubclass', 'SuppliesController@getsubclass');
    Route::get('supplies/geteditcategory', 'SuppliesController@geteditcategory');
    Route::get('pullcosting', 'FinishedProductController@pullcosting');
    Route::get('getselectedrmotherprod', 'OtherProductController@getselectedrmotherprod');
    Route::get('getpaymentterms', 'JobOrderController@getpaymentterms');
    Route::get('joborderdetail/{tnumber}/item/{jodetitem}/edit', 'JobOrderDetailsController@edit');
    Route::get('canceljoborder', 'JobOrderController@canceljoborder');
    Route::get('paymenttermsget', 'PurchasingController@paymenttermsget');
    Route::get('purchaseorderdetail/{tnumber}/item/{jodetitem}/edit', 'PurchaseOrderDetailsController@edit');
    Route::get('cancelpo', 'PurchasingController@cancelpo');
    Route::get('getpaymenttermstextfield', 'SalesOrderController@getpaymenttermstextfield');

    Route::get('getpurchaseorder', 'ReceivingController@getpurchaseorder');
    Route::get('receivingpodetail', 'ReceivingController@receivingpodetail');
    Route::get('cancelrr', 'ReceivingController@cancelrr');
    // Route::get('updatebal', ['as'=>'updatebal','uses'=>'ReceivingController@updatebal']);


    Route::get('production/{tnumber}/joborder', 'ProductionController@joborder');
    Route::get('production/{tnumber}/joborderbom', 'ProductionController@joborderbom');

    Route::get('getbranch', 'MaterialRequestController@getbranch');
    Route::get('materialrequest/{tnumber}/view', 'MaterialRequestController@view');
    Route::get('company/{tnumber}/view', 'CompaniesController@view');
    Route::get('branch/{tnumber}/view', 'BranchCompanyController@view');
    Route::get('location/{tnumber}/view', 'LocationController@view');
    Route::get('customer/{tnumber}/view', 'CustomerController@view');
    Route::get('paymentterm/{tnumber}/view', 'PaymentTermController@view');
    Route::get('vendors/{tnumber}/view', 'VendorController@view');
    Route::get('currency/{tnumber}/view', 'CurrencyController@view');
    Route::get('category/{tnumber}/view', 'CategoryController@view');
    Route::get('clss/{tnumber}/view', 'ClassController@view');
    Route::get('subclss/{tnumber}/view', 'SubClassController@view');
    Route::get('box/{tnumber}/view', 'BoxController@view');
    Route::get('packaging/{tnumber}/view', 'PackagingController@view');
    Route::get('unitofmeasure/{tnumber}/view', 'UnitOfMeasureController@view');
    Route::get('customer/{tnumber}/contact/{jodetitem}/view', 'ContactController@view');
    Route::get('vendors/{tnumber}/contact/{jodetitem}/view', 'VendorContactController@view');
    Route::get('rawmaterial/{tnumber}/view', 'RawMaterialController@view');
    Route::get('rawmaterial/{tnumber}/venditem/{jodetitem}/view', 'VendorItemController@view');
    Route::get('rawmaterial/{tnumber}/itempacking/{jodetitem}/view', 'ItemPackingController@view');
    Route::get('finishedproduct/{tnumber}/view', 'FinishedProductController@view');
    Route::get('finishedproduct/{tnumber}/otherproduct/{jodetitem}/view', 'OtherProductController@view');
    Route::get('finishedproduct/{tnumber}/bom/{jodetitem}/view', 'BillOfMaterialController@view');
    Route::get('finishedproduct/{tnumber}/finishedpacking/{jodetitem}/view', 'FinishedPackingController@view');
    Route::get('supplies/{tnumber}/view', 'SuppliesController@view');
    Route::get('supplies/{tnumber}/suppliesvendor/{jodetitem}/view', 'SuppliesVendorController@view');
    Route::get('supplies/{tnumber}/suppliesitempacking/{jodetitem}/view', 'SuppliesItemPackingController@view');

    Route::POST('purchasebalance/{id}/createpo','PurchaseBalanceController@createpo');
    Route::get('getaccess', 'UserGroupController@getaccess');
    Route::get('getaccesscreate', 'UserGroupController@getaccesscreate');
    Route::get('updateaccess', 'UserGroupController@updateaccess');
    Route::DELETE('contact/delcustcontact/{custcon}', 'ContactController@destroy');
    Route::PUT('customer/{custid}/custconupdate/{custcon}', 'ContactController@update');
    Route::PUT('vendors/{custid}/vendconupdate/{custcon}', 'VendorContactController@update');
    Route::DELETE('vendors/delvendcontact/{custcon}', '@destroy');
    Route::get('verifycode','VendorController@verifycode');
    Route::get('vendoritem-all-vendor','VendorController@vendorall');
    Route::POST('vendoritem-search','VendorController@vendorsearch');
    Route::POST('vendorsearchid','VendorController@vendorsearchid');
    Route::get('verifycoderawmat','ItemsController@verifycoderawmat');
    Route::get('findrawmaterial','ItemsController@findrawmaterial');
    Route::POST('rawmaterial-search','ItemsController@rawmaterialsearch');
    Route::POST('rawmaterialsearchid','ItemsController@rawmaterialsearchid');
    Route::get('otherproductverifycode','OtherProductController@otherproductverifycode');
    Route::post('otherproductsearch','OtherProductController@otherproductsearch');
    Route::get('finished-otherproduct','OtherProductController@otherproductall');
    Route::POST('otherproductsearchid','OtherProductController@otherproductsearchid');
    Route::POST('costingsave','FinishedProductController@costingsave');
    Route::POST('costingupdate','FinishedProductController@costingupdate');
    Route::POST('costchanges','RawMaterialController@costchanges');
    Route::get('getcostchanges','RawMaterialController@getcostchanges');
    Route::POST('suppliescostchanges','SuppliesController@suppliescostchanges');
    Route::get('suppliesgetcostchanges','SuppliesController@suppliesgetcostchanges');
    Route::get('getselectedrm', 'BillOfMaterialController@getselectedrm');
    Route::get('getdroppacking','BillOfMaterialController@getdroppacking');
    Route::PUT('resetpassword','UserSecurityController@resetpassword');
    Route::get('getselecteditempacking', 'JobOrderDetailsController@getselecteditempacking');
    Route::DELETE('joborderdetail/{tn}/jodetail/{item}', 'JobOrderDetailsController@destroy');
    Route::get('getjodsellingprice', 'JobOrderDetailsController@getjodsellingprice');
    Route::get('accessroles', 'UserGroupController@accessroles');
    Route::get('getposellingprice', 'PurchaseOrderDetailsController@getposellingprice');
    Route::DELETE('purchaseorderdetail/{tn}/podetail/{item}', 'PurchaseOrderDetailsController@destroy');
    Route::get('getrmcost', 'SalesOrderDetailController@getrmcost');
    Route::get('updateaup', 'SalesOrderDetailController@updateaup');
    Route::DELETE('salesorderdetail/{tn}/sod/{item}', 'SalesOrderDetailController@destroy');
    Route::get('salesorderdetail/{sodtnumber}/sodetail/{soditem}/edit', 'SalesOrderDetailController@edit');
    Route::get('getcurrencycustomer', 'SalesOrderController@currencycustomer');
    Route::get('getcurrencies', 'SalesOrderController@getcurrencies');
    Route::get('convertcurrency', 'SalesOrderController@convertcurrency');
    Route::get('currencyexcept', 'SalesOrderController@currencyexcept');
    Route::DELETE('currencyconvertion/{bcon}/convertion/{tarcon}', 'CurrencyconvertionController@destroy');
    Route::get('currencyconvertion/{cur1}', ['as'=>'createconvertions' ,'uses'=> 'CurrencyconvertionController@create']);
    Route::get('getcurrenciesrate', 'SalesOrderController@getcurrenciesrate');
    Route::get('getselectedrmformr', 'MaterialRequestDetailController@getselectedrmformr');


    Route::resource('company', 'CompaniesController');
    Route::resource('branch', 'BranchCompanyController');
    Route::resource('paymentterm', 'PaymentTermController');
    Route::resource('unitofmeasure', 'UnitOfMeasureController');
    Route::resource('customer', 'CustomerController');
    Route::resource('location', 'LocationController');
    Route::resource('box', 'BoxController');
    Route::resource('vendortype', 'VendorTypeController');
    Route::resource('vendors', 'VendorController');
    Route::resource('packaging', 'PackagingController');
    Route::resource('category', 'CategoryController');
    Route::resource('clss', 'ClassController');
    Route::resource('subclss', 'SubClassController');
    Route::resource('item', 'ItemsController');
    Route::resource('customer.contact', 'ContactController');
    Route::resource('vendors.contact', 'VendorContactController');
    Route::resource('rawmaterial', 'RawMaterialController');
    Route::resource('finishedproduct', 'FinishedProductController');
    Route::resource('rawmaterial.venditem', 'VendorItemController');
    Route::resource('rawmaterial.itempacking', 'ItemPackingController');
    Route::resource('finishedproduct.otherproduct', 'OtherProductController');
    Route::resource('finishedproduct.bom', 'BillOfMaterialController');
    Route::resource('finishedproduct.finishedpacking', 'FinishedPackingController');
    Route::resource('supplies', 'SuppliesController');
    Route::resource('supplies.suppliesvendor', 'SuppliesVendorController');

resources/views/compbranch/create.blade.php
@extends('layouts.layout')

@section('breadcrumbpage')
    <div class="row white-bg page-heading">
        <div class="col-lg-10">
            <h2>List of Companies</h2>
            {!! Breadcrumbs::render('branch') !!}
        </div>
        <div class="col-lg-2">

        </div>
    </div>
@endsection

@section('content')


    <div class="wrapper-content">
        <div class="row">
            <div class="col-lg-12">

                <div class="white-bg box-wrapper">
                    <div class="box-tool-bar">
                        <h5>Add Branch</h5>

                    </div>

                    <div class="box-content white-bg">
                        <div class="row">
                               <div class="col-lg-6">

                                  <form class="form-horizontal" method="post" action="{{ route('branch.store') }}">
                                      {{ csrf_field() }}
                                      <div class="form-group {{ $errors->has('code') ? ' has-error' : '' }}">
                                          <label class="col-sm-4 control-label">Code</label>

                                          <div class="col-sm-8">
                                              <input type="text" name="code"  value="{{ old('code') }}" class="form-control">
                                              @if ($errors->has('code'))
                                                  <span class="help-block">
                                                  <strong>{{ $errors->first('code') }}</strong>
                                                  </span>
                                              @endif
                                          </div>
                                      </div>



                                      <div class="form-group {{ $errors->has('name') ? ' has-error' : '' }}">
                                        <label class="col-sm-4 control-label">Name</label>

                                        <div class="col-sm-8">
                                            <input type="text" name="name"  value="{{ old('name') }}" class="form-control">
                                            @if ($errors->has('name'))
                                                <span class="help-block">
                                                  <strong>{{ $errors->first('name') }}</strong>
                                                  </span>
                                            @endif
                                        </div>
                                    </div>

                                      <div class="form-group {{ $errors->has('address') ? ' has-error' : '' }}">
                                          <label class="col-sm-4 control-label">Address</label>

                                          <div class="col-sm-8">
                                              <input type="text" name="address" value="{{ old('address') }}" class="form-control">
                                              @if ($errors->has('address'))
                                                  <span class="help-block">
                                                  <strong>{{ $errors->first('address') }}</strong>
                                                  </span>
                                              @endif

                                          </div>
                                      </div>

                                      <div class="form-group {{ $errors->has('zipcode') ? ' has-error' : '' }}">
                                          <label class="col-sm-4 control-label">ZipCode</label>

                                          <div class="col-sm-8">
                                              <input type="text" name="zipcode"  value="{{ old('zipcode') }}" class="form-control" placeholder="">
                                              @if ($errors->has('zipcode'))
                                                  <span class="help-block">
                                                  <strong>{{ $errors->first('zipcode') }}</strong>
                                                  </span>
                                              @endif
                                          </div>
                                      </div>

                                      <div class="form-group {{ $errors->has('_company') ? ' has-error' : '' }}">
                                          <label class="col-sm-4 control-label">Select Company</label>

                                          <div class="col-sm-8">
                                              <select name="_company" class="form-control">
                                                  <option></option>
                                                  @foreach($maincompany as $main)
                                                      <option value="{{ $main->id }}">{{ $main->name }}</option>
                                                  @endforeach    

                                              </select>
                                              @if ($errors->has('_company'))
                                                  <span class="help-block">
                                                  <strong>{{ $errors->first('_company') }}</strong>
                                                  </span>
                                              @endif
                                           </div>
                                      </div>




                                    <div class="form-group {{ $errors->has('tin') ? ' has-error' : '' }}">
                                        <label class="col-sm-4 control-label">Tin</label>

                                        <div class="col-sm-8">
                                            <input type="text" name="tin" value="{{ old('tin') }}" class="form-control">
                                            @if ($errors->has('tin'))
                                                <span class="help-block">
                                                  <strong>{{ $errors->first('tin') }}</strong>
                                                  </span>
                                            @endif
                                        </div>
                                    </div>

                                      <div class="form-group {{ $errors->has('glcode') ? ' has-error' : '' }}">
                                          <label class="col-sm-4 control-label">GL Code</label>

                                          <div class="col-sm-8">
                                              <input type="text" name="glcode" value="{{ old('glcode') }}" class="form-control">
                                              @if ($errors->has('glcode'))
                                                  <span class="help-block">
                                                  <strong>{{ $errors->first('glcode') }}</strong>
                                                  </span>
                                              @endif
                                          </div>
                                      </div>








                                    <div class="hr-line-dashed"></div>
                                    <div class="form-group">
                                        <div class="col-sm-6 col-sm-offset-4">
                                            <a href="{{ route('branch') }}" class="btn btn-white">Cancel</a>
                                            <button type="submit" class="btn btn-primary">Save </button>
                                        </div>
                                    </div>
                                </form>
                                </div>
                          </div>
                    </div>
                </div>

            </div>

        </div>
    </div>


@endsection



@section('customjs')

    <script src="{{ URL::asset('js/branchcompany.js') }}"></script>

@endsection

resources/views/compbranch/edit.blade.php
@extends('layouts.layout')

@section('breadcrumbpage')
    <div class="row white-bg page-heading">
        <div class="col-lg-10">
            <h2>List of Companies</h2>
            {!! Breadcrumbs::render('branch') !!}
        </div>
        <div class="col-lg-2">

        </div>
    </div>
@endsection

@section('content')


    <div class="wrapper-content">
        <div class="row">
            <div class="col-lg-12">

                <div class="white-bg box-wrapper">
                    <div class="box-tool-bar">
                        <h5>Edit Company</h5>

                    </div>

                    <div class="box-content white-bg">
                        <div class="row">
                               <div class="col-lg-6">

                                  <form  class="form-horizontal" method="POST" action="{{ route('branch.update',$company->id) }}">
                                      {{ csrf_field() }}

                                      <input type="hidden" name="_method" value="PUT">
                                      <div class="form-group">
                                          <label class="col-sm-4 control-label">Code</label>

                                          <div class="col-sm-8">
                                              <input type="text" name="code"  value="{{ $company->code }}" class="form-control">

                                          </div>
                                      </div>


                                    <div class="form-group {{ $errors->has('name') ? ' has-error' : '' }}">
                                        <label class="col-sm-4 control-label">Name</label>

                                        <div class="col-sm-8">
                                            <input type="text" name="name"  value="{{ $company->name }}" class="form-control">
                                            @if ($errors->has('name'))
                                                <span class="help-block">
                                                  <strong>{{ $errors->first('name') }}</strong>
                                                  </span>
                                            @endif
                                        </div>
                                    </div>

                                      <div class="form-group {{ $errors->has('address') ? ' has-error' : '' }}">
                                          <label class="col-sm-4 control-label">Address</label>

                                          <div class="col-sm-8">
                                              <input type="text" name="address" value="{{ $company->address }}" class="form-control">
                                              @if ($errors->has('address'))
                                                  <span class="help-block">
                                                  <strong>{{ $errors->first('address') }}</strong>
                                                  </span>
                                              @endif

                                          </div>
                                      </div>

                                      <div class="form-group {{ $errors->has('zipcode') ? ' has-error' : '' }}">
                                          <label class="col-sm-4 control-label">ZipCode</label>

                                          <div class="col-sm-8">
                                              <input type="text" name="zipcode"  value="{{ $company->zipcode }}" class="form-control" placeholder="">
                                              @if ($errors->has('zipcode'))
                                                  <span class="help-block">
                                                  <strong>{{ $errors->first('zipcode') }}</strong>
                                                  </span>
                                              @endif
                                          </div>
                                      </div>

                                      <div class="form-group {{ $errors->has('_company') ? ' has-error' : '' }}">
                                          <label class="col-sm-4 control-label">Select Company</label>

                                          <div class="col-sm-8">
                                              <select name="_company" class="form-control">
                                                  <option></option>
                                                  @foreach($maincompany as $main)

                                                      @if($main->id == $company->_company)
                                                          <option value="{{ $main->id }}" selected="selected">{{ $main->name }}</option>
                                                      @else
                                                        <option value="{{ $main->id }}">{{ $main->name }}</option>
                                                       @endif
                                                  @endforeach

                                              </select>
                                              @if ($errors->has('_company'))
                                                  <span class="help-block">
                                                  <strong>{{ $errors->first('_company') }}</strong>
                                                  </span>
                                              @endif
                                          </div>
                                      </div>





                                    <div class="form-group {{ $errors->has('tin') ? ' has-error' : '' }}">
                                        <label class="col-sm-4 control-label">Tin</label>

                                        <div class="col-sm-8">
                                            <input type="text" name="tin" value="{{ $company->tin }}" class="form-control">
                                            @if ($errors->has('tin'))
                                                <span class="help-block">
                                                  <strong>{{ $errors->first('tin') }}</strong>
                                                  </span>
                                            @endif
                                        </div>
                                    </div>


                                      <div class="form-group {{ $errors->has('glcode') ? ' has-error' : '' }}">
                                          <label class="col-sm-4 control-label">GL Code</label>

                                          <div class="col-sm-8">
                                              <input type="text" name="glcode" value="{{ $company->glcode }}" class="form-control">
                                              @if ($errors->has('glcode'))
                                                  <span class="help-block">
                                                  <strong>{{ $errors->first('glcode') }}</strong>
                                                  </span>
                                              @endif
                                          </div>
                                      </div>



                                      <div class="form-group">
                                          <div class="col-sm-6 col-sm-offset-4">
                                              <div>
                                                  <label>
                                                      @if($company->isactive)
                                                       <input type="checkbox" value="1" checked name="isactive">  Active
                                                      @else
                                                          <input type="checkbox" name="isactive">  Active

                                                      @endif

                                                  </label>
                                              </div>
                                          </div>
                                      </div>



                                      <div class="hr-line-dashed"></div>
                                    <div class="form-group">
                                        <div class="col-sm-6 col-sm-offset-4">
                                            <a href="{{ route('branch') }}" class="btn btn-white">Cancel</a>
                                            <button type="submit" class="btn btn-primary">Save </button>
                                        </div>
                                    </div>
                                </form>
                                </div>
                          </div>
                    </div>
                </div>

            </div>

        </div>
    </div>


@endsection



@section('customjs')

    <script src="{{ URL::asset('js/branchcompany.js') }}"></script>

@endsection

resources/views/compbranch/index.blade.php
@extends('layouts.layout')

@section('breadcrumbpage')
    <div class="row white-bg page-heading">
        <div class="col-lg-10">
            <h2>List of Branches</h2>
            {!! Breadcrumbs::render('branch') !!}
        </div>
        <div class="col-lg-2">

        </div>
    </div>
@endsection

@section('content')


    <div class="wrapper-content">
        <div class="row">
            <div class="col-lg-12">

                <div class="white-bg box-wrapper">

                    <div class="ibox-title">
                        <h5>Branch<small></small></h5>
                        <div class="ibox-tools">

                            {{--<a href="#" data-toggle="dropdown" class="dropdown-toggle">
                                <i class="fa fa-cog"></i>
                            </a>
                            <ul class="dropdown-menu">
                                <li><a href="{{ URL::to('branch/create') }}">Add Branch</a>
                                </li>

                            </ul>

--}}
                            <a class="btn btn-primary btn-rounded btn-sm" href="{{ URL::to('branch/create') }}">Add Branch</a>
                        </div>
                    </div>






                    <div class="box-content white-bg">
                        <div class="table-responsive">
                            <table width="100%" class="table table-bordered table-striped" id="company-branch-table">
                                <thead>
                                <tr>
                                    <th>Code</th>
                                    <th>Name</th>
                                    <th>Address</th>
                                    <th>Zip code</th>
                                    <th>Company</th>
                                    <th>Tin</th>
                                    <th></th>


                                </tr>
                                </thead>


                            </table>
                        </div>
                    </div>

                </div>

            </div>

        </div>
    </div>


@endsection


@section('customjs')

    <script src="{{ URL::asset('js/branchcompany.js') }}"></script>

@endsection